DROP TABLE IF EXISTS "Books";
CREATE TABLE "Books" ("BookId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "BookTitle" VARCHAR NOT NULL , "ISBN" VARCHAR NOT NULL , "PublishDate" VARCHAR NOT NULL , "Author" VARCHAR NOT NULL );
