//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDay.Console.DayServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayServiceReference.IServiceDay")]
    public interface IServiceDay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDay/GetDay", ReplyAction="http://tempuri.org/IServiceDay/GetDayResponse")]
        string GetDay(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDay/GetDay", ReplyAction="http://tempuri.org/IServiceDay/GetDayResponse")]
        System.Threading.Tasks.Task<string> GetDayAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDayChannel : WcfServiceDay.Console.DayServiceReference.IServiceDay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDayClient : System.ServiceModel.ClientBase<WcfServiceDay.Console.DayServiceReference.IServiceDay>, WcfServiceDay.Console.DayServiceReference.IServiceDay {
        
        public ServiceDayClient() {
        }
        
        public ServiceDayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDay(System.DateTime date) {
            return base.Channel.GetDay(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayAsync(System.DateTime date) {
            return base.Channel.GetDayAsync(date);
        }
    }
}
