//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5._2___5._6.Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Reports
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string ReportText { get; set; }
        public System.DateTime ReportTime { get; set; }
    }
}
