//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int WorkHoursLogsID { get; set; }
        public Nullable<System.DateTime> DateOld { get; set; }
        public string TaskOld { get; set; }
        public Nullable<int> HoursOld { get; set; }
        public string CommentOld { get; set; }
        public Nullable<int> EmployeeIDOld { get; set; }
        public Nullable<System.DateTime> DateNew { get; set; }
        public string TaskNew { get; set; }
        public Nullable<int> HoursNew { get; set; }
        public string CommentNew { get; set; }
        public Nullable<int> EmployeeIDNew { get; set; }
        public string IssuedCommand { get; set; }
        public Nullable<int> WorkHoursID { get; set; }
    }
}
