//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._1.Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Projects
    {
        public int EmployeeId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
